"""Point the cron at the actual kickoffs, rather than at office hours.

GitHub cron is static in the workflow file, so the schedule cannot know when
matches are. This regenerates it from the real fixture list: one entry per
distinct kickoff time, firing early enough that the watcher is already running
when lineups appear at T-60.

Kickoffs bundle. Five Saturday-three-o'clock fixtures publish their elevens at
the same moment and need one wake-up between them, not five.

Run weekly. The fixture list moves: matches are rescheduled for television, and
a kickoff time that changes after the schedule is written is a fixture whose
lineup we would miss.
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

WORKFLOW = Path(".github/workflows/lineups.yml")

# Fire before the watcher's own T-75 window, leaving room for GitHub's
# scheduler to run late, which it does under load.
LEAD = timedelta(minutes=100)

# GitHub rejects a workflow with too many schedule entries and throttles heavy
# users. A fortnight is plenty: this reruns weekly.
HORIZON_DAYS = 14

START = "    # BEGIN generated by foulgorithm.jobs.schedule"
END = "    # END generated"


def windows(fixtures, horizon_days: int = HORIZON_DAYS) -> list[datetime]:
    """One wake-up per distinct kickoff, earliest first, bundled and de-duplicated."""
    now = datetime.now(timezone.utc)
    limit = now + timedelta(days=horizon_days)
    times = {
        (f.kickoff_utc - LEAD).replace(second=0, microsecond=0)
        for f in fixtures
        if now < f.kickoff_utc <= limit
    }
    # Two kickoffs 90 minutes apart produce wake-ups that overlap the watcher's
    # own run, so the later one is redundant.
    out: list[datetime] = []
    for t in sorted(times):
        if out and (t - out[-1]) < timedelta(hours=2):
            continue
        out.append(t)
    return out


def cron_lines(times: list[datetime]) -> str:
    lines = [START]
    for t in times:
        lines.append(f"    # {t + LEAD:%a %d %b %H:%M} kickoff")
        lines.append(f'    - cron: "{t.minute} {t.hour} {t.day} {t.month} *"')
    lines.append(END)
    return "\n".join(lines)


SETTLE_WORKFLOW = Path(".github/workflows/settle.yml")

# How long after a matchday's LAST kickoff the settle wake fires. Must clear
# STATS_DELAY, the guard that defers a run while stats are still posting, with
# room for GitHub's scheduler running late, which it does under load. A wake
# that fired inside the delay would meet its own guard and the whole matchday
# would wait for the backstop cron.
SETTLE_LAG = timedelta(hours=3, minutes=45)

SETTLE_START = "    # BEGIN settle wakes generated by foulgorithm.jobs.schedule"
SETTLE_END = "    # END settle wakes"


def settle_windows(fixtures, horizon_days: int = HORIZON_DAYS) -> list[datetime]:
    """One wake per matchday, after its last match's stats have posted.

    Step 2 of docs/33-settle-schedule.md. The narrower the window between
    snapshots, the fewer players feature twice inside one, and a player who
    featured twice is unattributable and skipped forever.
    """
    now = datetime.now(timezone.utc)
    limit = now + timedelta(days=horizon_days)
    upcoming = [f.kickoff_utc for f in fixtures if now < f.kickoff_utc <= limit]

    last_per_day: dict = {}
    for kickoff in upcoming:
        day = kickoff.date()
        if day not in last_per_day or kickoff > last_per_day[day]:
            last_per_day[day] = kickoff

    return sorted(
        (kickoff + SETTLE_LAG).replace(second=0, microsecond=0)
        for kickoff in last_per_day.values()
    )


def rewrite_settle(fixtures, path: Path = SETTLE_WORKFLOW) -> int:
    """Rewrite settle.yml's generated block. 0 changed, 1 unchanged, 2 broken.

    The Monday and Thursday backstop crons stay: generated wakes add to them,
    never replace them, so a fortnight with no fixture list still settles.
    """
    times = settle_windows(fixtures)

    text = path.read_text()
    if SETTLE_START not in text or SETTLE_END not in text:
        print(f"{path} has no generated settle block to replace", file=sys.stderr)
        return 2

    lines = [SETTLE_START]
    for t in times:
        lines.append(f"    # stats posted for the {t - SETTLE_LAG:%a %d %b} matchday")
        lines.append(f'    - cron: "{t.minute} {t.hour} {t.day} {t.month} *"')
    lines.append(SETTLE_END)

    head, rest = text.split(SETTLE_START, 1)
    _, tail = rest.split(SETTLE_END, 1)
    updated = head + "\n".join(lines) + tail

    if updated == text:
        print(f"settle schedule unchanged, {len(times)} matchdays")
        return 1

    path.write_text(updated)
    print(f"settle schedule rewritten, {len(times)} matchday wakes")
    return 0


def run(path: Path = WORKFLOW) -> int:
    """Rewrite the generated block. Returns 0 if it changed, 1 if it did not."""
    from foulgorithm.sources import pulselive

    try:
        fixtures = [f for f in pulselive.fixtures() if f.status == pulselive.STATUS_UPCOMING]
    except Exception as exc:
        print(f"fixture list unavailable: {exc}", file=sys.stderr)
        return 2

    # Cup ties wake the watchers too. Lineup wakes only: the settle block
    # below never sees them, because an exhibition has nothing to settle.
    try:
        from types import SimpleNamespace

        from foulgorithm.publish import cup

        fixtures = fixtures + [
            SimpleNamespace(kickoff_utc=r["kickoff_utc"]) for r in cup.load_fixtures()
        ]
    except Exception as exc:  # noqa: BLE001 - a broken cup slate must not cost the league its wakes
        print(f"cup slate unreadable for wakes: {exc}", file=sys.stderr)

    times = windows(fixtures)
    if not times:
        print("no fixtures in the horizon")
        return 1

    text = path.read_text()
    if START not in text or END not in text:
        print(f"{path} has no generated block to replace", file=sys.stderr)
        return 2

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + cron_lines(times) + tail

    if updated == text:
        print(f"schedule unchanged, {len(times)} windows")
        return 1

    path.write_text(updated)
    print(f"schedule rewritten, {len(times)} windows:")
    for t in times[:6]:
        print(f"  wake {t:%a %d %b %H:%M} for the {t + LEAD:%H:%M} kickoff")
    if len(times) > 6:
        print(f"  ... and {len(times) - 6} more")
    return 0


def main() -> int:
    """Both schedules from one fixture read. Changed in either means changed."""
    from foulgorithm.sources import pulselive

    lineups_code = run()
    try:
        fixtures = [f for f in pulselive.fixtures() if f.status == pulselive.STATUS_UPCOMING]
    except Exception as exc:  # noqa: BLE001 - the lineups half already reported its own
        print(f"fixture list unavailable for settle wakes: {exc}", file=sys.stderr)
        return lineups_code
    settle_code = rewrite_settle(fixtures)
    if 2 in (lineups_code, settle_code):
        return 2
    return 0 if 0 in (lineups_code, settle_code) else 1


if __name__ == "__main__":
    raise SystemExit(main())
