"""Point the cron at the actual kickoffs, rather than at office hours.

GitHub cron is static in the workflow file, so the schedule cannot know when
matches are. This regenerates it from the real fixture list: one entry per
distinct kickoff time, firing early enough that the watcher is already running
when lineups appear at T-60.

Kickoffs bundle. Five Saturday-three-o'clock fixtures publish their elevens at
the same moment and need one wake-up between them, not five.

Run weekly. The fixture list moves: matches are rescheduled for television, and
a kickoff time that changes after the schedule is written is a fixture whose
lineup we would miss.
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

WORKFLOW = Path(".github/workflows/lineups.yml")

# Fire before the watcher's own T-75 window, leaving room for GitHub's
# scheduler to run late, which it does under load.
LEAD = timedelta(minutes=100)

# GitHub rejects a workflow with too many schedule entries and throttles heavy
# users. A fortnight is plenty: this reruns weekly.
HORIZON_DAYS = 14

START = "    # BEGIN generated by foulgorithm.jobs.schedule"
END = "    # END generated"


def windows(fixtures, horizon_days: int = HORIZON_DAYS) -> list[datetime]:
    """One wake-up per distinct kickoff, earliest first, bundled and de-duplicated."""
    now = datetime.now(timezone.utc)
    limit = now + timedelta(days=horizon_days)
    times = {
        (f.kickoff_utc - LEAD).replace(second=0, microsecond=0)
        for f in fixtures
        if now < f.kickoff_utc <= limit
    }
    # Two kickoffs 90 minutes apart produce wake-ups that overlap the watcher's
    # own run, so the later one is redundant.
    out: list[datetime] = []
    for t in sorted(times):
        if out and (t - out[-1]) < timedelta(hours=2):
            continue
        out.append(t)
    return out


def cron_lines(times: list[datetime]) -> str:
    lines = [START]
    for t in times:
        lines.append(f"    # {t + LEAD:%a %d %b %H:%M} kickoff")
        lines.append(f'    - cron: "{t.minute} {t.hour} {t.day} {t.month} *"')
    lines.append(END)
    return "\n".join(lines)


def run(path: Path = WORKFLOW) -> int:
    """Rewrite the generated block. Returns 0 if it changed, 1 if it did not."""
    from foulgorithm.sources import pulselive

    try:
        fixtures = [f for f in pulselive.fixtures() if f.status == pulselive.STATUS_UPCOMING]
    except Exception as exc:
        print(f"fixture list unavailable: {exc}", file=sys.stderr)
        return 2

    times = windows(fixtures)
    if not times:
        print("no fixtures in the horizon")
        return 1

    text = path.read_text()
    if START not in text or END not in text:
        print(f"{path} has no generated block to replace", file=sys.stderr)
        return 2

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + cron_lines(times) + tail

    if updated == text:
        print(f"schedule unchanged, {len(times)} windows")
        return 1

    path.write_text(updated)
    print(f"schedule rewritten, {len(times)} windows:")
    for t in times[:6]:
        print(f"  wake {t:%a %d %b %H:%M} for the {t + LEAD:%H:%M} kickoff")
    if len(times) > 6:
        print(f"  ... and {len(times) - 6} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
